name: Book a Padel court every Wednesday

on:
  schedule:
    # Runs at 23:50 PM UTC every Wednesday
    - cron: '* * * * *'
    #- cron: '0 23 * * 3'

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This is a scheduled task running!"
          # You can run your script or commands here
      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the Python script
        run: |
          python src/booking_bot.py